# Generated by Django 4.2 on 2023-05-23 11:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CMS.field')),
                ('value', models.CharField(max_length=200)),
            ],
            bases=('CMS.field',),
        ),
        migrations.CreateModel(
            name='ImageField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CMS.field')),
                ('value', models.ImageField(upload_to='images')),
            ],
            bases=('CMS.field',),
        ),
        migrations.CreateModel(
            name='RichTextField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CMS.field')),
                ('value', ckeditor.fields.RichTextField()),
            ],
            bases=('CMS.field',),
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CMS.field')),
                ('value', models.CharField(max_length=1000)),
            ],
            bases=('CMS.field',),
        ),
    ]
