# Generated by Django 4.2 on 2023-04-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='shoot',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='photo_site.shoot'),
            preserve_default='True',
        ),
    ]
