# Generated by Django 4.2 on 2023-04-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
