# Generated by Django 4.2 on 2023-05-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0006_alter_gallery_shoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='dominant_color',
            field=models.CharField(default='(228, 237, 230)', max_length=20),
        ),
    ]
