# Generated by Django 4.2 on 2023-05-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0007_gallery_dominant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='height',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='gallery',
            name='width',
            field=models.IntegerField(default=200),
        ),
    ]
