# Generated by Django 4.2 on 2023-05-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0008_gallery_height_gallery_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
