# Generated by Django 4.2 on 2023-06-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0009_gallery_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo')], default='photo', max_length=10),
        ),
    ]
