# Generated by Django 4.2 on 2023-06-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0010_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='embedded_video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
